### ISSUE TITLE
Better documentation around exporting packages into environment.yml

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/conda-env-update#22]
Could we get some better documentation in this README (and eventual Paketo docs) around how users can setup an environment.yml file when the conda packages have been installed? In my case, I setup a conda virtual env, installed my packages via, `conda install`, and exported into a environment.yml file via `conda env export > environment.yml`. With this, the build process were failing with a confusing error:
```
 Failed to run CONDA_PKGS_DIRS=/layers/paketo-community_conda-env-update/conda-env-cache conda env update --prefix /layers/paketo-community_conda-env-update/conda-env --file /workspace/environment.yml
        Collecting package metadata (repodata.json): ...working... done
        Solving environment: ...working... failed

        ResolvePackageNotFound:
          - openssl==1.1.1k=h9ed2024_0
          - markupsafe==2.0.1=py39h9ed2024_0
          - zlib==1.2.11=h1de35cc_3
          - importlib-metadata==3.10.0=py39hecd8cb5_0
          - ca-certificates==2021.4.13=hecd8cb5_1
          - python==3.9.5=h88f2d9e_3
          - certifi==2020.12.5=py39hecd8cb5_0
          - setuptools==52.0.0=py39hecd8cb5_0
          - tk==8.6.10=hb0a8c7a_0
          - libffi==3.3=hb1e8313_2
          - xz==5.2.5=h1de35cc_0
          - sqlite==3.35.4=hce871da_0
          - readline==8.1=h9ed2024_0
          - ncurses==6.2=h0a44026_1
          - libcxx==10.0.0=1
          - pip==21.1.1=py39hecd8cb5_0

ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 145
```

Turns out that this is all an architecture thing since I was running `conda install` on my Macbook. Running `conda env export --from-history > environment.yml` resolved this, so would be great if we could document this.

**Comment by fg-j** [comment]
@paketo-buildpacks/python-maintainers Is this user workflow still relevant to document?

**Comment by robdimsdale** [comment]
I don't know if this is still relevant, so I would like to keep this issue open while I investigate.
